language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update
  - pip install -U pip
  - pip install -U pytest
  - sudo apt-get install -y libopus0
  - sudo apt-get install -y mumble-server
  - sudo service mumble-server restart
install:
  - pip install -r ./requirements/requirements.txt
  - pip install -r ./requirements/web_server.txt
script:
  - pytest
