language: python
python:
  - "3.6"
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopus0
install:
  - pip install -r requirements.txt

# Run Tests
# Built-in Plugin Tests
script:
  - python tests/test_config.py
  - python tests/test_images.py
  - python tests/test_plugins.py