language: python
python:
  - "3.6"
  - "3.7"
dist: bionic
services: mysql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopus0
  - sudo apt-get install -y mumble-server
  - sudo service mumble-server restart
install:
  - pip install -r requirements.txt

# Run Tests
# Built-in Plugin Tests
script:
  - python JJMumbleBot/tests/test_cfg.py
