version: '3'
services:
  bot:
    build: .
    # Expose all ports to localhost
    network_mode: "host"
    volumes:
      - ./JJMumbleBot/cfg:/app/JJMumbleBot/cfg
    environment:
      - MUMBLE_IP=test
      - MUMBLE_PORT=64738
      - MUMBLE_PASSWORD=
    entrypoint: python /app

