version: '3'
services:
  bot:
    build: .
    # Expose all ports to localhost
    network_mode: "host"
    entrypoint: python /app 
    # This parameters can be overrided in docker-compose run command
    command: -ip 127.0.0.1 -port 64738
