version: '3.8'
services:
  bot:
    build: .
    # Expose all ports to localhost
    network_mode: "host"
    volumes:
      - ./JJMumbleBot/cfg:/app/JJMumbleBot/cfg
    environment:
      - MUMBLE_IP=localhost
      - MUMBLE_PORT=64738
      - MUMBLE_PASSWORD=

