name: docker
on: [push]
jobs:
  pull-and-build-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for develop branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: jjmumblebot # Provide Docker image name
        image-tag: head # Raise the flag to try to pull image
